{{ if .Values.install }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-{{ .Values.remote.couchbase.name }}
type: Opaque
data:
  username: {{ .Values.replication.username }}
  password: {{ .Values.replication.password }}
{{- end -}}
