---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: couchbasememcachedbuckets.couchbase.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.memoryQuota
    description: Maximum memory size in MiB of the bucket
    name: Memory Quota
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: couchbase.com
  names:
    categories:
    - all
    - couchbase
    kind: CouchbaseMemcachedBucket
    plural: couchbasememcachedbuckets
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            enableFlush:
              type: boolean
            memoryQuota:
              type: string
          required:
          - memoryQuota
          type: object
      type: object
  versions:
  - name: v1
    served: false
    storage: false
  - name: v2
    served: true
    storage: true

