---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: couchbasebackuprestores.couchbase.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.CapacityUsed
    description: total size of the backup volume
    name: Capacity Used
    type: string
  - JSONPath: .status.LastRun
    description: last time backup was run
    name: Last Run
    type: string
  - JSONPath: .status.LastSuccess
    description: last time restore was successful
    name: Last Success
    type: string
  - JSONPath: .status.Duration
    name: Duration
    type: string
  - JSONPath: .status.Running
    name: Running
    type: boolean
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: couchbase.com
  names:
    categories:
    - all
    - couchbase
    kind: CouchbaseBackupRestore
    plural: couchbasebackuprestores
    shortNames:
    - cbrestore
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            backup:
              type: string
            end:
              properties:
                int:
                  minimum: 1
                  type: integer
                str:
                  type: string
              type: object
            logRetention:
              pattern: ^\d+(ns|us|ms|s|m|h)$
              type: string
            repo:
              type: string
            start:
              properties:
                int:
                  minimum: 1
                  type: integer
                str:
                  type: string
              type: object
          required:
          - backup
          - start
          type: object
        status:
          properties:
            archive:
              type: string
            completed:
              type: boolean
            duration:
              type: string
            failed:
              type: boolean
            job:
              type: string
            lastfailure:
              type: string
            lastrun:
              type: string
            lastsuccess:
              type: string
            output:
              type: string
            pod:
              type: string
            repo:
              type: string
            running:
              type: boolean
          type: object
  versions:
  - name: v1
    served: false
    storage: false
  - name: v2
    served: true
    storage: true
