---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: couchbasebackups.couchbase.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.strategy
    description: what backup strategy is being followed
    name: Strategy
    type: string
  - JSONPath: .spec.size
    description: total size of the backup volume
    name: Volume Size
    type: string
  - JSONPath: .status.CapacityUsed
    description: total size of the backup volume
    name: Capacity Used
    type: string
  - JSONPath: .status.LastRun
    description: last time backup was run
    name: Last Run
    type: string
  - JSONPath: .status.LastSuccess
    description: last time backup was successful
    name: Last Success
    type: string
  - JSONPath: .status.Running
    name: Running
    type: boolean
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: couchbase.com
  names:
    categories:
    - all
    - couchbase
    kind: CouchbaseBackup
    plural: couchbasebackups
    shortNames:
    - cbbackup
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            backupRetention:
              pattern: ^\d+(ns|us|ms|s|m|h)$
              type: string
            failedJobsHistoryLimit:
              minimum: 0
              type: integer
            full:
              properties:
                schedule:
                  type: string
              required:
              - schedule
              type: object
            incremental:
              properties:
                schedule:
                  type: string
              required:
              - schedule
              type: object
            logRetention:
              pattern: ^\d+(ns|us|ms|s|m|h)$
              type: string
            size:
              type: string
            strategy:
              pattern: ^full_incremental|full_only$
              type: string
            successfulJobsHistoryLimit:
              minimum: 0
              type: integer
          required:
          - strategy
          type: object
        status:
          properties:
            archive:
              type: string
            capacityused:
              type: string
            cronjob:
              type: string
            duration:
              type: string
            failed:
              type: boolean
            job:
              type: string
            lastfailure:
              type: string
            lastrun:
              type: string
            lastsuccess:
              type: string
            output:
              type: string
            pod:
              type: string
            repo:
              type: string
            repolist:
              type: object
            running:
              type: boolean
          type: object
  versions:
  - name: v1
    served: false
    storage: false
  - name: v2
    served: true
    storage: true

