{{ $tls := fromYaml ( include "couchbase-cluster.tls" . ) }}
{{ if .Values.tls.generate }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.tls.operator-secret" . }}
data:
  ca.crt: {{ $tls.caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.tls.server-secret" . }}
data:
  chain.pem: {{ $tls.clientCert }}
  pkey.key: {{ $tls.clientKey }}
{{- end -}}
{{- if not .Values.syncGateway.configSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.sg.name" . }}
data:
  config.json: {{ include "couchbase-cluster.sg.json-config" . | b64enc }}
{{- if .Values.syncGateway.cacert }}
  ca.pem: {{ (toString .Values.syncGateway.cacert | b64enc) }}
{{- else if .Values.tls.generated }}
  ca.pem: {{ $tls.clientCert }}
{{- end -}}
{{- end -}}
