---
apiVersion: "couchbase.com/v2"
kind: "CouchbaseCluster"
metadata:
  name: {{ template "couchbase-cluster.clustername" . }}
spec:
  image: {{ .Values.couchbaseCluster.image }}
  networking:
    exposeAdminConsole: {{ .Values.couchbaseCluster.exposeAdminConsole }}
    adminConsoleServices: {{ .Values.couchbaseCluster.adminConsoleServices }}
    exposedFeatures: {{ .Values.couchbaseCluster.exposedFeatures }}
    adminConsoleServiceType: {{ .Values.couchbaseCluster.adminConsoleServiceType }}
    exposedFeatureServiceType: {{ .Values.couchbaseCluster.exposedFeatureServiceType }}
  security:
    adminSecret: {{ template "couchbase-cluster.secret.name" . }}
    rbac:
      managed: {{ .Values.couchbaseCluster.security.rbac.managed }}
{{- if .Values.couchbaseCluster.dns }}
  dns:
    domain: {{ .Values.couchbaseCluster.dns.domain }}
{{- end }}
{{- if .Values.couchbaseCluster.platform }}
  platform: {{ .Values.couchbaseCluster.platform }}
{{- end }}
  cluster:
{{ toYaml .Values.couchbaseCluster.cluster | indent 4 }}
  buckets:
    managed: {{ .Values.couchbaseCluster.buckets.managed }}
  servers:
  {{- range $server, $config := .Values.couchbaseCluster.servers }}
  - name: {{ $server }}
{{ toYaml $config | indent 4 }}
  {{- end }}
{{- if .Values.couchbaseTLS.create }}
  tls:
    static:
      member:
        serverSecret: {{ template "couchbase-cluster.secret.tls-server" . }}
      operatorSecret: {{ template "couchbase-cluster.secret.tls-operator" . }}
{{- end }}
  securityContext:
{{ toYaml .Values.couchbaseCluster.securityContext | indent 4 }}
  volumeClaimTemplates:
{{ toYaml .Values.couchbaseCluster.volumeClaimTemplates | indent 4 }}
  logRetentionTime: {{ .Values.couchbaseCluster.logRetentionTime }}
  logRetentionCount: {{ .Values.couchbaseCluster.logRetentionCount }}
