{{ $tls := fromYaml ( include "couchbase-cluster.gen-certs" . ) }}
{{- if .Values.couchbaseTLS.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.secret.tls-operator" . }}
data:
  ca.crt: {{ $tls.caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.secret.tls-server" . }}
data:
  chain.pem: {{ $tls.clientCert }}
  pkey.key: {{ $tls.clientKey }}
{{- end -}}
{{- if not .Values.syncGateway.configSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.sg.name" . }}
data:
  config.json: {{ include "couchbase-cluster.sg.json-config" . | b64enc }}
{{- if .Values.syncGateway.cacert }}
  ca.pem: {{ (toString .Values.syncGateway.cacert | b64enc) }}
{{- else if .Values.couchbaseTLS.create  }}
  ca.pem: {{ $tls.clientCert }}
{{- end -}}
{{- end -}}
