{{- if .Values.syncGateway.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "couchbase-cluster.sg.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "couchbase-cluster.chart" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "couchbase-cluster.sg.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "couchbase-cluster.sg.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "couchbase-cluster.sg.name" . }}
    spec:
      containers:
      - name: sync-gateway
        image: "{{ .Values.syncGateway.image.repository }}:{{ .Values.syncGateway.image.tag }}"
        imagePullPolicy: {{ .Values.syncGateway.imagePullPolicy }}
        volumeMounts:
        - mountPath: /etc/sync_gateway
          name: config
          readOnly: true
        env:
        - name: GOMAXPROCS
          value: "1"
      volumes:
      - name: config
        secret:
          secretName: {{ template "couchbase-cluster.sg.name" . }}
{{- end -}}
