{{- if .Values.syncGateway.create -}}
---
# {{ template "couchbase-cluster.sg.json-config" .  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "couchbase-cluster.sg.name" . }}
data:
  config.json: {{ include "couchbase-cluster.sg.json-config" . | b64enc }}
{{- end -}}
